import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "./mainLayout";
import { dbconfig } from "@/utils/dbconfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbconfig();
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout children={children} />
      </body>
    </html>
  );
}
