export const data = [
  {
    id: 1,
    name: "Basic",
    price: "Free",
    prof: "3 Staffs",
    benefits: [
      "VS Code",
      "NextJS",
      "Javascript",
      "Freeword press Themes",
      "5 Domain support",
    ],
    URL: "register/Basic",
  },
  {
    id: 2,
    name: "Standard",
    price: "500",
    prof: "10 Staffs",
    benefits: [
      "All Basic",
      "VS Code",
      "NextJS",
      "Javascript",
      "Freeword press Themes",
      "15 Domain support",
      "Email support",
    ],
    URL: "register/Standard",
  },
  {
    id: 3,
    name: "Premium",
    price: "1000",
    prof: "Unlimited",
    benefits: [
      "All Standard",
      "VS Code",
      "NextJS",
      "Javascript",
      "Freeword press Themes",
      "15 Domain support",
      "Email support",
      "comment support",
    ],
    URL: "register/Premium",
  },
];
